* 关于
  :PROPERTIES:
  :CUSTOM_ID: about
  :END:

我，男，16 年本科毕业，数字媒体技术专业，工作是扮演一个程序员，主要从事 DevOps/运维平台开发方向。

我似乎比较宅，不过有出去旅游的机会我也不会放过，对 Python 非常感兴趣（我也不知道为啥），
喜欢听音乐，看电影，但是基本无个人见解。

个人业余时间喜欢学习 Python 相关的知识，包括 Python 最佳实践，Python 底层运行原理。
此外，为了更好的掌握 Python，也会有节奏的补充一些 MySQL，Redis，操作系统，计算机网络等方面的基础知识。

工作方面使用到的技术主要是 Python(Flask+Django) + React， 有时也会接触 Kubernetes 相关知识。

这里用于记录一些自己的碎碎念，包括旅游，编程，音乐，电影相关的东西。
成文的笔记会放在这里 [[http://cosven.me][个人博客]]，Python 相关的好的文章或者视频会记在 [[http://blog.pyzh.org][pyzh-blog]]。

** 笔记的记录准则
*** 笔记的分类（一切的基础）
笔记大体分三类：工作，生活，兴趣爱好。兴趣爱好是分散在工作和生活中的。

索引
- 重要事情以及当下事情一览：工作看 notes, 生活看 evernote，evernote 上可以包含一部分工作的索引
- 思考总结类：evernote, blogs, notes
- 临时计划类：TODO list, evernote
- 项目类：Docs, issues
- 零碎积累：cosven.github.io

按公私分：
- 公：blogs, cosven.github.io, issues, docs, todo list
- 私：evernote, Dropbox/notes

按类型分
- 工作：Docs, TODO list, Dropbox/notes
  - 工作短期计划（无沉淀价值的）：TODO list（飞书）
  - 工作长期关注（有沉淀价值的）：Dropbox/notes
    由于这类事情部分是私有的，所以不能直接放在和公司绑定的软件上。
    evernote 也是一个考虑的选项，但它有两个问题：一方面 evernote 要收费，没有 linux 版；
    另一方面，虑工作和生活能够有序的隔离是比较好的，而 evernote 只包含生活的。
  - 工作项目记录：Goolge Docs/Feishu Docs
- 生活：evernote
  - 生活短期计划（无沉淀价值的）：evernote
    没有特别好的方法。之前尝试过记在 life_tracking 里面，但是那样太分散了。
  - 生活长期关注（有沉淀和记录价值的）：
    - 记录计划与细节：evernote
    - 思考总结类：evernote
- 兴趣爱好: cosven.github.io, blogs, evernote
  - 技术类分两种（比如 FeelUOwn）
    - 临时记录：cosven.github.io
    - 有思考并且有深度：blogs
  - 生活类（比如听歌）
    - 临时记录：evernote。
    - 有思考并且有深度：blogs, evernote。

*** 一些小的事情、事件没必要记录时间
重要的事情可以放在大事件里面，大事件中的事情可以记录时间。

*** todo list 和细节可以适当分离
如果我们想把 todo 和细节放在一起，那么这个 todo 必须是一个 header，
而纵观这么多 org html theme，它们一般都只支持 3 层 header。而一个 todo
往往会由多个小 todo 组成，如果我们将 todo 和细节放在一起，渲染效果会比较差。

*** todo 与 checkbox
一个大的 todo 最好是一个项目，一些小任务是 checkbox，
小任务的实现过程或者细节可以写在一个单独的地方，然后将链接写在 checkbox 后。

*** 少用 3 级标题，不要用 4 级标题
这里的 3 级标题对应 HTML 的 h4，这里的 4 级标题在各个 HTML theme 中都非常难看。
