* Web 开发
** ANSWERED [#B] MySQL like vs select all?
有一个用户表，它只有 4 个字段： =(id, name, gender, is_deleted)= ，
其中，id 是主键，name + env 是唯一的。现在有一个需求场景，前端有一个搜索框，
用户在输入字符时，前端需要进行自动补全，返回 5 个最相似的男性用户名。

解决方案：

1. 不建立索引
  1. select * from user where name like '%keyword%' and gender='male' and is_deleted=false
  2. 返回前五行
2. 建立联合索引 (name, gender, is_deleted)
  1. select * from user where gender='male' and is_deleted=false;
  2. 业务代码中进行相似度计算
3. ...

附加题：

1. 如果这个表还有两个字段：created_at, updated_at 呢？
2. 如果这个表有 100w+ 条数据呢？

后来：它们说这个需求不适合 MySQL，用 es 把。如果非要用 MySQL，
like 也不是不可以。

** TODO [#B] REST methods and status code 和 CSRF 保护
1. [[https://stackoverflow.com/questions/28459418/rest-api-put-vs-patch-with-real-life-examples][stackoverflow: put vs patch with real life example]]
2. [[http://restcookbook.com/HTTP%20Methods/idempotency/][rest methods idempotency]]
3. [[https://tools.ietf.org/html/rfc7231#section-6.5.8][409 status code]]
4. [[https://stackoverflow.com/a/32101994/4302892][how to do batch update]]

** Test Doubles — Fakes, Mocks and Stubs
[[https://blog.pragmatists.com/test-doubles-fakes-mocks-and-stubs-1a7491dfa3da][文章链接]]

- mock: mock 掉的对象是被测的对象。比如我们断言某一个函数会被调用，但又不想真正执行该函数，用 mock
- stub: stub 掉的对象不是被测的对象，它是用来配合测试的。比如一个死板的人造的符合预期的数据
- fake: 对实际系统的简单模拟。比如 python fakeredis。

#+BEGIN_QUOTE
Fakes are objects that have working implementations, but not same as production one. Usually they take some shortcut and have simplified version of production code.

Stub is an object that holds predefined data and uses it to answer calls during tests. It is used when we cannot or don’t want to involve objects that would answer with real data or have undesirable side effects.

Mocks are objects that register calls they receive.
In test assertion we can verify on Mocks that all expected actions were performed.
#+END_QUOTE

附加参考资料： https://martinfowler.com/bliki/TestDouble.html
